version: '3'

services:
  my-express-bolierplate:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./database:/usr/src/app/database